<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert sample Laravel users for authentication
        DB::table('users')->insert([
            [
                'id' => 1,
                'first_name' => 'John',
                'last_name' => 'Manager',
                'username' => 'jmanager',
                'email' => 'jmanager@loanmgt.com',
                'phone_no' => '+855-12-123456',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now()->subHours(2),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'first_name' => 'Sarah',
                'last_name' => 'Loan Officer',
                'username' => 'sloan',
                'email' => 'sloan@loanmgt.com',
                'phone_no' => '+855-12-234567',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now()->subHours(1),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'first_name' => 'Michael',
                'last_name' => 'Teller',
                'username' => 'mteller',
                'email' => 'mteller@loanmgt.com',
                'phone_no' => '+855-12-345678',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now()->subMinutes(30),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'first_name' => 'Lisa',
                'last_name' => 'Cashier',
                'username' => 'lcashier',
                'email' => 'lcashier@loanmgt.com',
                'phone_no' => '+855-12-456789',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now()->subMinutes(45),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'first_name' => 'David',
                'last_name' => 'Supervisor',
                'username' => 'dsupervisor',
                'email' => 'dsupervisor@loanmgt.com',
                'phone_no' => '+855-12-567890',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now()->subHours(3),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'first_name' => 'Emma',
                'last_name' => 'Analyst',
                'username' => 'eanalyst',
                'email' => 'eanalyst@loanmgt.com',
                'phone_no' => '+855-12-678901',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now()->subHours(1),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'first_name' => 'Robert',
                'last_name' => 'Admin',
                'username' => 'radmin',
                'email' => 'radmin@loanmgt.com',
                'phone_no' => '+855-12-789012',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now()->subMinutes(15),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'first_name' => 'Jenny',
                'last_name' => 'Customer Service',
                'username' => 'jcustomer',
                'email' => 'jcustomer@loanmgt.com',
                'phone_no' => '+855-12-890123',
                'password' => Hash::make('password123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now()->subMinutes(20),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'first_name' => 'Admin',
                'last_name' => 'System',
                'username' => 'admin',
                'email' => 'admin@loanmgt.com',
                'phone_no' => '+855-23-123456',
                'password' => Hash::make('admin123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now(),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'first_name' => 'Demo',
                'last_name' => 'User',
                'username' => 'demo',
                'email' => 'demo@loanmgt.com',
                'phone_no' => '+855-23-234567',
                'password' => Hash::make('demo123'),
                'email_verified_at' => now(),
                'is_verified' => true,
                'last_login' => now()->subMinutes(5),
                'avartar' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
